- title: 论文封面
  icon: basic-elaboration-smartphone-heart
  content: 提供顶刊论文封面设计
- title: 内容插图
  icon: basic-elaboration-message-happy
  content: 提供精美插图设计
- title: PPT润色
  icon: basic-lightbulb
  content: 让你的PPT更迷人